export const countries = [
  { code: "+66", name: "Thailand", flag: "🇹🇭" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+855", name: "Cambodia", flag: "🇰🇭" },
  { code: "+1", name: "United States", flag: "🇺🇸" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+81", name: "Japan", flag: "🇯🇵" },
  { code: "+82", name: "South Korea", flag: "🇰🇷" },
  { code: "+65", name: "Singapore", flag: "🇸🇬" },
  { code: "+60", name: "Malaysia", flag: "🇲🇾" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+63", name: "Philippines", flag: "🇵🇭" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+44", name: "United Kingdom", flag: "🇬🇧" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+7", name: "Russia", flag: "🇷🇺" },
  { code: "+971", name: "UAE", flag: "🇦🇪" },
];

export const productCategories = [
  { value: "fashion", label: "Fashion & Accessories" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "food", label: "Food & Beverages" },
  { value: "home", label: "Home & Living" },
  { value: "mother_baby", label: "Mother & Baby" },
  { value: "toys", label: "Toys & Hobbies" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "automotive", label: "Automotive" },
  { value: "health", label: "Health & Wellness" },
  { value: "pet", label: "Pet Supplies" },
  { value: "office", label: "Office & Stationery" },
  { value: "tools", label: "Tools & Home Improvement" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "digital", label: "Digital Products" },
  { value: "others", label: "Others" },
];