export const countries = [
  { code: "+66", name: "Thailand", flag: "🇹🇭" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+855", name: "Cambodia", flag: "🇰🇭" },
  { code: "+1", name: "United States", flag: "🇺🇸" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+81", name: "Japan", flag: "🇯🇵" },
  { code: "+82", name: "South Korea", flag: "🇰🇷" },
  { code: "+65", name: "Singapore", flag: "🇸🇬" },
  { code: "+60", name: "Malaysia", flag: "🇲🇾" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+63", name: "Philippines", flag: "🇵🇭" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+44", name: "United Kingdom", flag: "🇬🇧" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+7", name: "Russia", flag: "🇷🇺" },
  { code: "+971", name: "UAE", flag: "🇦🇪" },
];

// Commercial banks operating in Laos. Used by the shop opening flow's
// Bank Name dropdown so seller-entered bank names stay consistent and
// the admin's payout sheet doesn't have to deal with free-text typos.
// "OTHER" is intentional — covers regional / branch banks not in this list.
export const laoBanks = [
  "BCEL — Banque pour le Commerce Extérieur Lao",
  "LDB — Lao Development Bank",
  "APB — Agricultural Promotion Bank",
  "Nayoby Bank",
  "JDB — Joint Development Bank",
  "Phongsavanh Bank",
  "Indochina Bank",
  "ST Bank (Sacombank Lao)",
  "Maruhan Japan Bank Lao",
  "Lao Construction Bank (LCB)",
  "BIC Bank Lao",
  "BFL — Banque Franco-Lao",
  "LVB — Lao-Viet Bank",
  "Vietinbank Lao",
  "Acleda Bank Lao",
  "SBI Lao",
  "Public Bank Lao",
  "RHB Bank Lao",
  "First Commercial Bank Vientiane Branch",
  "Bangkok Bank Vientiane Branch",
  "Krung Thai Bank Vientiane Branch",
  "Vietcombank Vientiane Branch",
  "ICBC Vientiane Branch",
  "Bank of China Vientiane Branch",
  "Other",
];

export const productCategories = [
  { value: "fashion", label: "Fashion & Accessories" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "food", label: "Food & Beverages" },
  { value: "home", label: "Home & Living" },
  { value: "mother_baby", label: "Mother & Baby" },
  { value: "toys", label: "Toys & Hobbies" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "automotive", label: "Automotive" },
  { value: "health", label: "Health & Wellness" },
  { value: "pet", label: "Pet Supplies" },
  { value: "office", label: "Office & Stationery" },
  { value: "tools", label: "Tools & Home Improvement" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "digital", label: "Digital Products" },
  { value: "others", label: "Others" },
];